# Generated by Django 5.2.15 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('classe', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('imagem', models.URLField(max_length=500)),
                ('tipo', models.CharField(choices=[('jogador', 'Jogador'), ('npc', 'NPC')], default='jogador', max_length=10)),
                ('raca', models.CharField(max_length=80)),
                ('alinhamento', models.CharField(max_length=80)),
                ('campanha', models.CharField(max_length=120)),
                ('antecedente', models.CharField(max_length=120)),
                ('local', models.CharField(max_length=120)),
                ('faccao', models.CharField(max_length=120)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['nome'],
            },
        ),
    ]
